var annotated_dup =
[
    [ "bilayers", "namespacebilayers.html", [
      [ "Bilayer2D", "classbilayers_1_1_bilayer2_d.html", "classbilayers_1_1_bilayer2_d" ]
    ] ],
    [ "Eigen", "namespace_eigen.html", [
      [ "NumTraits< oILAB::Rational< IntScalarType > >", "struct_eigen_1_1_num_traits_3_01o_i_l_a_b_1_1_rational_3_01_int_scalar_type_01_4_01_4.html", "struct_eigen_1_1_num_traits_3_01o_i_l_a_b_1_1_rational_3_01_int_scalar_type_01_4_01_4" ]
    ] ],
    [ "inverse_design_core", "namespaceinverse__design__core.html", [
      [ "InverseDesignResult", "classinverse__design__core_1_1_inverse_design_result.html", "classinverse__design__core_1_1_inverse_design_result" ]
    ] ],
    [ "layers", "namespacelayers.html", [
      [ "BasisAtom", "classlayers_1_1_basis_atom.html", "classlayers_1_1_basis_atom" ],
      [ "Layer2D", "classlayers_1_1_layer2_d.html", "classlayers_1_1_layer2_d" ]
    ] ],
    [ "oILAB", "namespaceo_i_l_a_b.html", [
      [ "BestRationalApproximation", "classo_i_l_a_b_1_1_best_rational_approximation.html", "classo_i_l_a_b_1_1_best_rational_approximation" ],
      [ "BiCrystal", "classo_i_l_a_b_1_1_bi_crystal.html", "classo_i_l_a_b_1_1_bi_crystal" ],
      [ "BicrystalActor", "structo_i_l_a_b_1_1_bicrystal_actor.html", "structo_i_l_a_b_1_1_bicrystal_actor" ],
      [ "CanonicalTP", "classo_i_l_a_b_1_1_canonical_t_p.html", "classo_i_l_a_b_1_1_canonical_t_p" ],
      [ "Diff", "classo_i_l_a_b_1_1_diff.html", "classo_i_l_a_b_1_1_diff" ],
      [ "DiophantineSolver", "classo_i_l_a_b_1_1_diophantine_solver.html", "classo_i_l_a_b_1_1_diophantine_solver" ],
      [ "DislocationDipole", "classo_i_l_a_b_1_1_dislocation_dipole.html", "classo_i_l_a_b_1_1_dislocation_dipole" ],
      [ "Dislocations", "classo_i_l_a_b_1_1_dislocations.html", "classo_i_l_a_b_1_1_dislocations" ],
      [ "DisplacementKernel", "classo_i_l_a_b_1_1_displacement_kernel.html", "classo_i_l_a_b_1_1_displacement_kernel" ],
      [ "Ensemble", "classo_i_l_a_b_1_1_ensemble.html", "classo_i_l_a_b_1_1_ensemble" ],
      [ "EvolutionAlgorithm", "classo_i_l_a_b_1_1_evolution_algorithm.html", "classo_i_l_a_b_1_1_evolution_algorithm" ],
      [ "Exponential", "classo_i_l_a_b_1_1_exponential.html", "classo_i_l_a_b_1_1_exponential" ],
      [ "Fraction", "structo_i_l_a_b_1_1_fraction.html", "structo_i_l_a_b_1_1_fraction" ],
      [ "Function", "classo_i_l_a_b_1_1_function.html", "classo_i_l_a_b_1_1_function" ],
      [ "Gb", "classo_i_l_a_b_1_1_gb.html", "classo_i_l_a_b_1_1_gb" ],
      [ "GbContinuum", "classo_i_l_a_b_1_1_gb_continuum.html", "classo_i_l_a_b_1_1_gb_continuum" ],
      [ "GbMaterialTensors", "classo_i_l_a_b_1_1_gb_material_tensors.html", "classo_i_l_a_b_1_1_gb_material_tensors" ],
      [ "GbMesoState", "classo_i_l_a_b_1_1_gb_meso_state.html", "classo_i_l_a_b_1_1_gb_meso_state" ],
      [ "GbMesoStateEnsemble", "classo_i_l_a_b_1_1_gb_meso_state_ensemble.html", "classo_i_l_a_b_1_1_gb_meso_state_ensemble" ],
      [ "GbShifts", "classo_i_l_a_b_1_1_gb_shifts.html", "classo_i_l_a_b_1_1_gb_shifts" ],
      [ "GramMatrix", "classo_i_l_a_b_1_1_gram_matrix.html", "classo_i_l_a_b_1_1_gram_matrix" ],
      [ "HhatInvFunction", "classo_i_l_a_b_1_1_hhat_inv_function.html", "classo_i_l_a_b_1_1_hhat_inv_function" ],
      [ "IntegerLattice", "classo_i_l_a_b_1_1_integer_lattice.html", "classo_i_l_a_b_1_1_integer_lattice" ],
      [ "IntegerMath", "structo_i_l_a_b_1_1_integer_math.html", "structo_i_l_a_b_1_1_integer_math" ],
      [ "LandauWangTP", "classo_i_l_a_b_1_1_landau_wang_t_p.html", "classo_i_l_a_b_1_1_landau_wang_t_p" ],
      [ "Lattice", "classo_i_l_a_b_1_1_lattice.html", "classo_i_l_a_b_1_1_lattice" ],
      [ "LatticeCore", "structo_i_l_a_b_1_1_lattice_core.html", "structo_i_l_a_b_1_1_lattice_core" ],
      [ "LatticeDirection", "structo_i_l_a_b_1_1_lattice_direction.html", "structo_i_l_a_b_1_1_lattice_direction" ],
      [ "LatticeFunction", "classo_i_l_a_b_1_1_lattice_function.html", "classo_i_l_a_b_1_1_lattice_function" ],
      [ "LatticeVector", "classo_i_l_a_b_1_1_lattice_vector.html", "classo_i_l_a_b_1_1_lattice_vector" ],
      [ "LLL", "classo_i_l_a_b_1_1_l_l_l.html", "classo_i_l_a_b_1_1_l_l_l" ],
      [ "MatrixDimIExt", "classo_i_l_a_b_1_1_matrix_dim_i_ext.html", "classo_i_l_a_b_1_1_matrix_dim_i_ext" ],
      [ "MatrixDimIExt< IntScalarType, 1 >", "classo_i_l_a_b_1_1_matrix_dim_i_ext_3_01_int_scalar_type_00_011_01_4.html", "classo_i_l_a_b_1_1_matrix_dim_i_ext_3_01_int_scalar_type_00_011_01_4" ],
      [ "MesoState", "classo_i_l_a_b_1_1_meso_state.html", "classo_i_l_a_b_1_1_meso_state" ],
      [ "MesoStateEnsemble", "classo_i_l_a_b_1_1_meso_state_ensemble.html", "classo_i_l_a_b_1_1_meso_state_ensemble" ],
      [ "MonteCarlo", "classo_i_l_a_b_1_1_monte_carlo.html", "classo_i_l_a_b_1_1_monte_carlo" ],
      [ "oiViewerMainWindow", "structo_i_l_a_b_1_1oi_viewer_main_window.html", "structo_i_l_a_b_1_1oi_viewer_main_window" ],
      [ "oiViewerVTKwidget", "structo_i_l_a_b_1_1oi_viewer_v_t_kwidget.html", "structo_i_l_a_b_1_1oi_viewer_v_t_kwidget" ],
      [ "Operator", "classo_i_l_a_b_1_1_operator.html", "classo_i_l_a_b_1_1_operator" ],
      [ "OperatorScalarProduct", "classo_i_l_a_b_1_1_operator_scalar_product.html", "classo_i_l_a_b_1_1_operator_scalar_product" ],
      [ "OperatorSum", "classo_i_l_a_b_1_1_operator_sum.html", "classo_i_l_a_b_1_1_operator_sum" ],
      [ "OrderedTuplet", "classo_i_l_a_b_1_1_ordered_tuplet.html", "classo_i_l_a_b_1_1_ordered_tuplet" ],
      [ "PeriodicFunction", "classo_i_l_a_b_1_1_periodic_function.html", "classo_i_l_a_b_1_1_periodic_function" ],
      [ "Rational", "structo_i_l_a_b_1_1_rational.html", "structo_i_l_a_b_1_1_rational" ],
      [ "RationalApproximations", "classo_i_l_a_b_1_1_rational_approximations.html", "classo_i_l_a_b_1_1_rational_approximations" ],
      [ "RationalLatticeDirection", "structo_i_l_a_b_1_1_rational_lattice_direction.html", "structo_i_l_a_b_1_1_rational_lattice_direction" ],
      [ "RationalMatrix", "classo_i_l_a_b_1_1_rational_matrix.html", "classo_i_l_a_b_1_1_rational_matrix" ],
      [ "RationalReciprocalLatticeDirection", "structo_i_l_a_b_1_1_rational_reciprocal_lattice_direction.html", "structo_i_l_a_b_1_1_rational_reciprocal_lattice_direction" ],
      [ "ReciprocalLatticeDirection", "structo_i_l_a_b_1_1_reciprocal_lattice_direction.html", "structo_i_l_a_b_1_1_reciprocal_lattice_direction" ],
      [ "ReciprocalLatticeVector", "classo_i_l_a_b_1_1_reciprocal_lattice_vector.html", "classo_i_l_a_b_1_1_reciprocal_lattice_vector" ],
      [ "ReferenceState", "classo_i_l_a_b_1_1_reference_state.html", "classo_i_l_a_b_1_1_reference_state" ],
      [ "RLLL", "classo_i_l_a_b_1_1_r_l_l_l.html", "classo_i_l_a_b_1_1_r_l_l_l" ],
      [ "Shift", "classo_i_l_a_b_1_1_shift.html", "classo_i_l_a_b_1_1_shift" ],
      [ "ShiftedDisplacementKernelFT", "classo_i_l_a_b_1_1_shifted_displacement_kernel_f_t.html", "classo_i_l_a_b_1_1_shifted_displacement_kernel_f_t" ],
      [ "SmithDecomposition", "classo_i_l_a_b_1_1_smith_decomposition.html", "classo_i_l_a_b_1_1_smith_decomposition" ],
      [ "SmithDecomposition< 1 >", "classo_i_l_a_b_1_1_smith_decomposition_3_011_01_4.html", "classo_i_l_a_b_1_1_smith_decomposition_3_011_01_4" ],
      [ "StaticID", "classo_i_l_a_b_1_1_static_i_d.html", "classo_i_l_a_b_1_1_static_i_d" ],
      [ "StringToScalar", "structo_i_l_a_b_1_1_string_to_scalar.html", "structo_i_l_a_b_1_1_string_to_scalar" ],
      [ "StringToScalar< double >", "structo_i_l_a_b_1_1_string_to_scalar_3_01double_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01double_01_4" ],
      [ "StringToScalar< float >", "structo_i_l_a_b_1_1_string_to_scalar_3_01float_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01float_01_4" ],
      [ "StringToScalar< int >", "structo_i_l_a_b_1_1_string_to_scalar_3_01int_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01int_01_4" ],
      [ "StringToScalar< long >", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01_4" ],
      [ "StringToScalar< long double >", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01double_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01double_01_4" ],
      [ "StringToScalar< long long >", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01long_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01long_01long_01_4" ],
      [ "StringToScalar< unsigned long >", "structo_i_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01_4" ],
      [ "StringToScalar< unsigned long long >", "structo_i_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01long_01_4.html", "structo_i_l_a_b_1_1_string_to_scalar_3_01unsigned_01long_01long_01_4" ],
      [ "TextFileParser", "classo_i_l_a_b_1_1_text_file_parser.html", "classo_i_l_a_b_1_1_text_file_parser" ],
      [ "XTuplet", "classo_i_l_a_b_1_1_x_tuplet.html", "classo_i_l_a_b_1_1_x_tuplet" ]
    ] ],
    [ "pyoilab", "namespacepyoilab.html", [
      [ "PyLatticeDirection", "classpyoilab_1_1_py_lattice_direction.html", "classpyoilab_1_1_py_lattice_direction" ],
      [ "PyLatticeVector", "classpyoilab_1_1_py_lattice_vector.html", "classpyoilab_1_1_py_lattice_vector" ],
      [ "PyReciprocalLatticeDirection", "classpyoilab_1_1_py_reciprocal_lattice_direction.html", "classpyoilab_1_1_py_reciprocal_lattice_direction" ],
      [ "PyReciprocalLatticeVector", "classpyoilab_1_1_py_reciprocal_lattice_vector.html", "classpyoilab_1_1_py_reciprocal_lattice_vector" ]
    ] ],
    [ "FFT", "class_f_f_t.html", "class_f_f_t" ],
    [ "range", "classrange.html", "classrange" ],
    [ "Rotation", "class_rotation.html", "class_rotation" ]
];